### ISSUE TITLE
MIUI点击搜索到的结果会FC

### ISSUE THREAD

**Issue by wydy** [cloud-emoticon/cloudemoticon-android#30]
![screenshot_2017-04-08-00-02-41-470_org ktachibana cloudemoji](https://cloud.githubusercontent.com/assets/1937986/24808623/17da63b0-1b82-11e7-9f11-6129e4a54667.png)

**Comment by KTachibanaM** [comment]
请打开 查看日志摘要 给我看

**Comment by wydy** [comment]
logcat
![screenshot_2017-04-08-20-15-13-415_com alcatraz fclogcat](https://cloud.githubusercontent.com/assets/1937986/24828812/874b6e84-1c2b-11e7-9715-4c6371439226.png)
