### ISSUE TITLE
收藏的表情显示不全

### ISSUE THREAD

**Issue by Undefined-User** [cloud-emoticon/cloudemoticon-android#31]
每次打开时随机显示一定数量的已收藏表情，但是不会全部显示(也可能啥都不显示)，查看database没有发现问题，下面是一些问题复现的截图，版本是来自GooglePlay的v1.1.1(已加beta计划)，从1.1.0beta版开始出现此问题
<img src="https://ooo.0o0.ooo/2017/04/22/58fb5914c4d9a.png" width="300">
<img src="https://ooo.0o0.ooo/2017/04/22/58fb595e08e95.png" width="300">
<img src="https://ooo.0o0.ooo/2017/04/22/58fb595e26804.png" width="300">
<img src="https://ooo.0o0.ooo/2017/04/22/58fb595e6dc48.png" width="300">
<img src="https://ooo.0o0.ooo/2017/04/22/58fb595e80fa3.png" width="300">
<img src="https://ooo.0o0.ooo/2017/04/22/58fb595e9d8cf.png" width="300">
<img src="https://ooo.0o0.ooo/2017/04/22/58fb595f1c023.png" width="300">

**Comment by KTachibanaM** [comment]
请问你的Android版本是什么

**Comment by KTachibanaM** [comment]
请试一下这个版本
[app-debug.apk.zip](https://github.com/cloud-emoticon/cloudemoji/files/949929/app-debug.apk.zip)

**Comment by Undefined-User** [comment]
MIUI Global 8.2.2.0,Android6.0.1，KT发过来的debug版本已没有此问题，下面是截图
https://ooo.0o0.ooo/2017/04/24/58fd84b9af9b3.png
另外关于 #30 里提到的点击搜索结果fc问题，我这里也存在，下面是MIUI自带的日志摘要截图
https://ooo.0o0.ooo/2017/04/24/58fd84ba8b182.png

**Comment by KTachibanaM** [comment]
Without logs it would be hard to debug the issue
